### ISSUE TITLE
react-html5-qrcode-reader not working in react 18

### ISSUE THREAD

**Issue by juanele121976** [briosheje/react-html5-qrcode-reader#1]
hi, great componente but, not working in react 18

**Comment by briosheje** [comment]
Will check it now, it should be working though.

**Comment by briosheje** [comment]
@juanele121976 it looks like it is working with react 18, see this stackblitz for reference: https://react-ts-wzhrqh.stackblitz.io

Can you please replicate the issue somewhere?

**Comment by juanele121976** [comment]
Hello, sorry for the inconvenience, I did the test but I could not install the component in react.js I get an error

thank you very much in advance

$ npm i react-html5-qrcode-reader
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: pwa-app@0.1.0
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"^18.2.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^17.0.0" from react-html5-qrcode-reader@1.1.0
npm ERR! node_modules/react-html5-qrcode-reader
npm ERR!   react-html5-qrcode-reader@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\GBA-PC\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\GBA-PC\AppData\Local\npm-cache\_logs\2022-11-22T19_54_21_304Z-debug.log

**Comment by briosheje** [comment]
> Hello, sorry for the inconvenience, I did the test but I could not install the component in react.js I get an error
> 
> thank you very much in advance
> 
> $ npm i react-html5-qrcode-reader npm ERR! code ERESOLVE npm ERR! ERESOLVE unable to resolve dependency tree npm ERR! npm ERR! While resolving: pwa-app@0.1.0 npm ERR! Found: react@18.2.0 npm ERR! node_modules/react npm ERR! react@"^18.2.0" from the root project npm ERR! npm ERR! Could not resolve dependency: npm ERR! peer react@"^17.0.0" from react-html5-qrcode-reader@1.1.0 npm ERR! node_modules/react-html5-qrcode-reader npm ERR! react-html5-qrcode-reader@"*" from the root project npm ERR! npm ERR! Fix the upstream dependency conflict, or retry npm ERR! this command with --force, or --legacy-peer-deps npm ERR! to accept an incorrect (and potentially broken) dependency resolution. npm ERR! npm ERR! See C:\Users\GBA-PC\AppData\Local\npm-cache\eresolve-report.txt for a full report.
> 
> npm ERR! A complete log of this run can be found in: npm ERR! C:\Users\GBA-PC\AppData\Local\npm-cache_logs\2022-11-22T19_54_21_304Z-debug.log

Ooooh I see, sounds like a peer dependency issue from my side, I should update the package.json accordingly indeed!

**Comment by briosheje** [comment]
@juanele121976 should be closed with https://github.com/briosheje/react-html5-qrcode-reader/commit/bfe6bf8223410705df1193f2597f597396001107

Please update to version 1.1.1 (https://www.npmjs.com/package/react-html5-qrcode-reader/v/1.1.1), the error should disappear.

**Comment by juanele121976** [comment]
thank you very much for your time and solution
